name: CI Pipeline

on:
  push:
    branches: [ main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@y5

    - name: Set up Node.js
      uses: actions/setup-node@y3
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
